version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      rust-runtime:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /sdk/web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /deploy/docker
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
